remote_theme: mmistakes/minimal-mistakes

author:
  name: Bhushan S. Mapari
  avatar: https://avatars.githubusercontent.com/BhushGb
  links:
    - label: GitHub
      url: https://github.com/YOUR_USERNAME
    - label: LinkedIn
      url: https://linkedin.com/in/your
    - label: Email
      url: mailto:you@example.com
